# Openshift AI configuration.
# If set to enabled, it release the RHOAI Operator and setup DSCI and DSC.
rhoai:
  enabled: true
  components:
    kueue:
      enabled: true
  services:
    monitoring:
      enabled: true

# Dependencies configuration for operators
# Each dependency can be enabled/disabled and configured here
dependencies:
  - name: cert-manager
    enabled: "{{ .Values.rhoai.components.kueue.enabled }}"
    namespace: cert-manager-operator
    subscription:
      name: openshift-cert-manager-operator
      channel: stable-v1
  - name: kueue
    enabled: "{{ .Values.rhoai.components.kueue.enabled }}"
    namespace: openshift-kueue-operator
    subscription:
      name: kueue-operator
      channel: stable-v1.1
  - name: opentelemetry-product
    enabled: "{{ .Values.rhoai.services.monitoring.enabled }}"
    namespace: openshift-opentelemetry-operator
    subscription:
      name: opentelemetry-product
      channel: stable
  - name: cluster-observability-operator
    enabled: "{{ .Values.rhoai.services.monitoring.enabled }}"
    namespace: openshift-cluster-observability-operator
    subscription:
      name: cluster-observability-operator
      channel: stable
