apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kuadrant.yaml
  - post-install-job.yaml

configMapGenerator:
  - name: authorino-ssl-config
    namespace: kuadrant-system
    files:
      - ssl-authorino.yaml
